name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.METRICS_SECRET }}
          committer_message: "refresh profile metrics [skip ci]"
          user: sahil-m416
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  metrics:
    needs: isocalendar
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.METRICS_SECRET }}
          committer_message: "refresh profile metrics [skip ci]"
          user: sahil-m416
          template: classic
          base: activity
          config_timezone: Asia/Kolkata
          config_order: languages, base.activity
          plugin_languages: yes
