name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

permissions:
  contents: write

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_SECRET }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: sahil-m416
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
